Q1,2,3 license changed for documentation
ssm-lab/capstone--source-code-optimizer pull request #11
Opened 2024-09-19 06:17 UTC by mmyaaaaa

2024-09-19 17:52 UTC, Sevhena requested changes
Please look at above comment

2024-09-19 17:52 UTC, Sevhena commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +The code in this repo is provided free to use under the MIT License.
Conflicts with the license @tbrar06 is proposing

2024-09-20 12:56 UTC, Sevhena commented
@mmyaaaaa Please do the changes mentioned above and rename the pull request with the appropriate naming convention ( [DELIVERABLE #] <Changed Doc>: Add Section <#s> ).

2024-09-21 19:38 UTC, Ayushi1972 approved these changes
Looks good. The license will be updated after @tbrar06 Pull Request gets approved.

2024-09-22 04:28 UTC, mmyaaaaa reviewed
Changes done ready to merge

2024-09-22 17:43 UTC, Sevhena approved these changes
LGTM

2024-09-23 03:36 UTC, merged