[Deliverable 3] Hazard Analysis: Intro and scope/ purpose
ssm-lab/capstone--source-code-optimizer pull request #146
Opened 2024-10-14 07:21 UTC by mmyaaaaa

## Description
Added intro and scope and purpose of hazard analysis 
Closes #145 

## How Has This Been Tested?
This is documentation - not applicable

2024-10-14 17:29 UTC, Ayushi1972 approved these changes
LGTM

2024-10-14 17:41 UTC, Sevhena requested changes

2024-10-14 17:41 UTC, Sevhena commented on docs/HazardAnalysis/HazardAnalysis.tex
> +As noted in lecture, a hazard is defined as a property or condition in the system,
Just cite and this and you should be good, the rest looks great

2024-10-16 19:59 UTC, Sevhena approved these changes
LGTM

2024-10-16 20:00 UTC, merged