[Deliverable 2] SRS: Tasks Section
ssm-lab/capstone--source-code-optimizer pull request #81
Opened 2024-10-04 21:31 UTC by Ayushi1972

## Description
Tasks section complete

## How Has This Been Tested?
Compiled locally

2024-10-05 22:58 UTC, Sevhena requested changes
Just a couple notes on the scope of our project. Might need to omit post deployment aspects (since its a capstone project).

2024-10-05 22:58 UTC, Sevhena commented on docs/SRS/SRS.tex
> +        \item Pull changes from the appropriate epic branch (dev or docs)
```suggestion
        \item Pull changes from \texttt{docs} (epic documentation branch)
```

2024-10-05 22:58 UTC, Sevhena commented on docs/SRS/SRS.tex
> +    \item Provide post-launch support
Is this relevant to us?

2024-10-05 22:58 UTC, Sevhena commented on docs/SRS/SRS.tex
> +        \item Post-launch support resources should be allocated
Related to previous question

2024-10-05 22:58 UTC, Sevhena commented on docs/SRS/SRS.tex
> +        \item A phased deployment approach will help minimize disruption
Might need to be re-worded since our project isn't already on the market, we aren't really disrupting anything. Maybe more accurate to mention phased _development_ rather than _deployment_

2024-10-06 07:01 UTC, mmyaaaaa approved these changes
LGTM

2024-10-06 10:23 UTC, Sevhena approved these changes
LGTM

2024-10-06 15:12 UTC, nivethakuruparan commented
Remember to squash and merge and not just merge

2024-10-06 17:25 UTC, merged